// Generated by https://quicktype.io

export interface PastLaunches {
  flight_number: number;
  mission_name: string;
  mission_id: string[];
  launch_year: string;
  launch_date_unix: number;
  launch_date_utc: string;
  launch_date_local: string;
  is_tentative: boolean;
  tentative_max_precision: TentativeMaxPrecision;
  tbd: boolean;
  launch_window: number | null;
  rocket: Rocket;
  ships: string[];
  telemetry: Telemetry;
  launch_site: LaunchSite;
  launch_success: boolean | null;
  links: Links;
  details: null | string;
  upcoming: boolean;
  static_fire_date_utc: null | string;
  static_fire_date_unix: number | null;
  timeline: null;
  crew: unknown[] | null;
  last_date_update?: string;
  last_ll_launch_date?: null | string;
  last_ll_update?: null | string;
  last_wiki_launch_date?: string;
  last_wiki_revision?: string;
  last_wiki_update?: string;
  launch_date_source?: LaunchDateSource;
}

enum LaunchDateSource {
  Wiki = "wiki",
}

interface LaunchSite {
  site_id: SiteID;
  site_name: SiteName;
  site_name_long: SiteNameLong;
}

enum SiteID {
  CcafsSlc40 = "ccafs_slc_40",
  KscLc39A = "ksc_lc_39a",
  VafbSlc4E = "vafb_slc_4e",
}

enum SiteName {
  CcafsSlc40 = "CCAFS SLC 40",
  KscLc39A = "KSC LC 39A",
  VafbSlc4E = "VAFB SLC 4E",
}

enum SiteNameLong {
  CapeCanaveralAirForceStationSpaceLaunchComplex40 = "Cape Canaveral Air Force Station Space Launch Complex 40",
  KennedySpaceCenterHistoricLaunchComplex39A = "Kennedy Space Center Historic Launch Complex 39A",
  VandenbergAirForceBaseSpaceLaunchComplex4E = "Vandenberg Air Force Base Space Launch Complex 4E",
}

interface Links {
  mission_patch: null | string;
  mission_patch_small: undefined | string;
  reddit_campaign: string;
  reddit_launch: string;
  reddit_recovery: null | string;
  reddit_media: null | string;
  presskit: null;
  article_link: null | string;
  wikipedia: null | string;
  video_link: string;
  youtube_id: string;
  flickr_images: string[];
}

interface Rocket {
  rocket_id: RocketID;
  rocket_name: RocketName;
  rocket_type: RocketType;
  first_stage: FirstStage;
  second_stage: SecondStage;
  fairings: Fairings | null;
}

interface Fairings {
  reused: boolean | null;
  recovery_attempt: boolean | null;
  recovered: boolean | null;
  ship: null | string;
}

interface FirstStage {
  cores: Core[];
}

interface Core {
  core_serial: string;
  flight: number;
  block: number;
  gridfins: boolean;
  legs: boolean;
  reused: boolean;
  land_success: boolean;
  landing_intent: boolean;
  landing_type: LandingType;
  landing_vehicle: string;
}

enum LandingType {
  Asds = "ASDS",
  Rtls = "RTLS",
}

enum RocketID {
  Falcon9 = "falcon9",
}

enum RocketName {
  Falcon9 = "Falcon 9",
}

enum RocketType {
  Ft = "FT",
}

interface SecondStage {
  block: number;
  payloads: Payload[];
}

interface Payload {
  payload_id: string;
  norad_id: number[];
  reused: boolean;
  customers: string[];
  nationality: Nationality;
  manufacturer: null | string;
  payload_type: PayloadType;
  payload_mass_kg: number | null;
  payload_mass_lbs: number | null;
  orbit: string;
  orbit_params: OrbitParams;
  cap_serial?: string;
  mass_returned_kg?: null;
  mass_returned_lbs?: null;
  flight_time_sec?: null;
  cargo_manifest?: null;
}

enum Nationality {
  Argentina = "Argentina",
  SouthKorea = "South Korea",
  UnitedStates = "United States",
}

interface OrbitParams {
  reference_system: ReferenceSystem;
  regime: string;
  longitude: null;
  semi_major_axis_km: number | null;
  eccentricity: number | null;
  periapsis_km: number | null;
  apoapsis_km: number | null;
  inclination_deg: number | null;
  period_min: number | null;
  lifespan_years: number | null;
  epoch: null | string;
  mean_motion: number | null;
  raan: number | null;
  arg_of_pericenter: number | null;
  mean_anomaly: number | null;
}

enum ReferenceSystem {
  Geocentric = "geocentric",
}

enum PayloadType {
  CrewDragon = "Crew Dragon",
  Satellite = "Satellite",
}

interface Telemetry {
  flight_club: null;
}

enum TentativeMaxPrecision {
  Hour = "hour",
}
